### ISSUE TITLE
Add a 'raw data' viewer like PVRTexTool

### ISSUE THREAD

**Issue by applecuckoo** [bluescan/tacentview#166]
Basically something like this:
![raw](https://github.com/bluescan/tacentview/assets/113647417/d1e9104f-d5be-4496-933c-0b6e25f5e07d)

**Comment by bluescan** [comment]
This pvrtextool dialog is for wrapping existing raw data with the pvr header... tacentview does not yet support saving pvr files. However, it may be reasonable to allow display of 'raw' pixel data if you happen to know the pixel-format, dimensions, mipmaps etc. Will leave this request open but may not get to it for a while. Thx for the suggestion.

**Comment by bluescan** [comment]
Tentative plan here is to make a 'raw import' dialog. The dialog would allow specification of the filetype to create (only lossless filetypes much like the paste filetypes).

Fields of the raw-import dialog would include:
* Filename
* Pixel Data Offset (default 0)
* Pixel format. Would include BC / ASTC / Packed / ETC / EAC / PVR but probably not palettized or vendor-specific formats.
* Width / Height
* Mipmaps (default off) 
* Colour profile (specifies both colour-space and LDR/HDR). This is less ambiguous than just a colour-space because quite often the space of the RGB components is sRGB while the alpha is linear).
* Premultiplied alpha (for formats that support an alpha channel, if premult was true we would need to 'undo' it by multiplying by the reciprocal of the alpha).

Note: Updating display 'live' would be needed so different dimensions / offsets could be experimented with on the fly.
Note: Care would have to be taken that we don't ever overrun the available data by pre-computing the needed buffer size given the width/height/mips/pixel-format. This would then be compared to the actual size of the data being imported (filesize - offset) and if too little data not performing an import. Would need a warning message of some kind.

**Comment by bluescan** [comment]
<img width="478" alt="image" src="https://github.com/bluescan/tacentview/assets/19311462/54af8782-4530-4132-bb54-c84bbe84aa34">
Still ToDo:
* Allow changing filetype in same import session.
* Support the remaining filetypes (TIFF, APNG, WEBP done, TGA, PNG, QOI, and BMP not).
* Implement the 'live' checkbox.
* Colour profile selection.
* Create test raw images with and without mipmaps/offsets. Make sure rows are not reversed etc.
* Better messaging when import fails (decode error, not enough data, etc).

**Comment by bluescan** [comment]
This is the final version of the import dialog. Will close this issue after testing a few more raw files.
<img width="664" alt="image" src="https://github.com/bluescan/tacentview/assets/19311462/4dbdc5ea-1e27-4200-a490-9093fac25d73">

**Comment by bluescan** [comment]
Commit ee73529ed9d1bad6e72c18b0143dac7e9dc4c0fd includes various raw test images.
