### ISSUE TITLE
Packaging for Nix

### ISSUE THREAD

**Issue by poperigby** [bluescan/tacentview#176]
This is a followup to #175. I got Tacent View to build and run, but there's a slight problem. When I try to run it, it's attempting to create a data directory in the location of its binary:

```console
Exe /nix/store/6fw6asfwq4fi64lvp3805k5qdap772i4-tacentview-1.0.44/bin/tacentview
Tacent View V 1.0.44
Tacent Library V 0.8.17
Dear ImGui V 1.89.2
GLFW V 3.3.2
For CLI Mode: tacentview --cli --help
terminate called after throwing an instance of 'std::filesystem::__cxx11::filesystem_error'
  what():  filesystem error: cannot create directory: Read-only file system [/nix/store/6fw6asfwq4fi64lvp3805k5qdap772i4-tacentview-1.0.44/bin/Data]
fish: Job 1, '/nix/store/aqpzwh5ww5mnkh21a77w…' terminated by signal SIGABRT (Abort)
```

The problem is, the location of the binary is the Nix store, and that's read only. Is there a way to get Tacent View to put this `Data` directory somewhere else?

**Comment by bluescan** [comment]
Try pulling 5926183921dd3690fdb32b1fe1c81ac58393ef55 or later. Then configure with 
-DPACKAGE_NIX=True

I'm not super familiar with NIX but with Snap there are specific env vars set that tell the viewer where to put stuff (e.g. SNAP_USER_DATA and SNAP_USER_COMMON)... when passing in -DPACKAGE_SNAP the compiled viewer will read those env vars to get (and put) stuff in the right place.  It looks like there are also env vars for NIX ( https://nix.dev/manual/nix/2.22/command-ref/env-common ) but I'm not 100% sure what they resolve to.

In particular the viewer needs 3 variables set correctly, the folder for static data (icons etc), where the config file should be saved, and where it should store cache data (like thumbnails). If you look for @poperigby in TacentView.cpp you will see it is (now) using NIX_DATA_DIR based on the link above for the static data. That may or may not be correct... I wasn't sure if it was package-specific... so you'd need to check and/or modify. In any case it needs to be wherever you/NIX is packaging all the stuff in the Data directory. It then uses ~/.tacentview for the other two. There may be a better place for both of these in the Nix world...again not sure.

If I'm wrong in assuming what those env vars are for... the paths can be set explicitly for NIX builds in the cpp since it's now in a separate ifdef block... anything you do in there will only compile if PACKAGE_NIX is set.

**Comment by bluescan** [comment]
Also worth noting that the locations of the 3 variables are now printed out when you run the viewer. Helpful for debugging. Look for "LocInfo:" in the output. It prints them for any combination of platform (Windows/Linux) and package define (PACKAGE_SNAP, PACKAGE_DEB, PACKAGE_NIX)

**Comment by bluescan** [comment]
Once the three vars are set correctly, tacentview will not try to create the Data directory. That is for static data only. It will try to create the directories storing the config file and cache dir though. The problem was for other platforms we put the cache/cfg inside the Data dir.

**Comment by poperigby** [comment]
Thanks for your help. Still trying to get it working with GLX. It isn't finding it for some reason. I'll keep you updated.

**Comment by bluescan** [comment]
sounds good. Incidentally this thread has given me the impetus to try getting tacentview to be more compliant with XDG base directories: https://specifications.freedesktop.org/basedir-spec/latest/
In particular I shouldn't be using $HOME/.tacentview at all. There may be a commit or two relating to this in the near future.

**Comment by bluescan** [comment]
Things have changed/improved underneath you just a little -- wanted to simplify the folder structure. As of 05dc4deedc80a5f41f142b8bf7c0f992b90786e7 the viewer supports XDG for PACKAGE_NIX (and PACKAGE_DEB). The tGetXDG calls can be used even if "use-xdg-base-directories" is not set because tacent returns appropriate defaults when calling tGetXDG*. There are separate directories for cache and config (XDG helps here... no more $HOME/.tacentview).

Also there is no more 'Data' directory. It's now called 'Assets' and under no conditions will the viewer write into it. It's assets only (button images, icons, etc). Without any PACKAGE_ specifier, the development layout is used: Assets, Config, Cache all in the same folder as the exe. This is so it never interferes with anything that may be installed on the system whether it be Nix, snap, deb, whatever.

**Comment by poperigby** [comment]
Great! 

Do you happen to have any insight on why Tacent View isn't able to find GLX?

```
Glfw Error 65542: GLX: Failed to load GLX
```

I don't think it's a Nix issue, because I don't see any other OpenGL applications doing anything special with GLX. I've included `libGL` as a dependency.

**Comment by poperigby** [comment]
Also, I'm running into some trouble with the actual installation of Tacent View. Pardon me if I'm wrong (I don't know too much about CMake), but it seems that these variables aren't being respected, leading to Tacent View not being installed correctly. 

```
Manually-specified variables were not used by the project:
  BUILD_TESTING
  CMAKE_EXPORT_NO_PACKAGE_REGISTRY
  CMAKE_INSTALL_BINDIR
  CMAKE_INSTALL_DOCDIR
  CMAKE_INSTALL_INCLUDEDIR
  CMAKE_INSTALL_INFODIR
  CMAKE_INSTALL_LIBDIR
  CMAKE_INSTALL_LIBEXECDIR
  CMAKE_INSTALL_LOCALEDIR
  CMAKE_INSTALL_MANDIR
  CMAKE_INSTALL_OLDINCLUDEDIR
  CMAKE_INSTALL_SBINDIR
  CMAKE_POLICY_DEFAULT_CMP0025
```

The libraries and binaries aren't ending up in the right spot.

**Comment by bluescan** [comment]
I know you figured out the GLX error. Coincidentally I was getting the exact same issue packaging the snap about 30 minutes ago... which I also figured out. Incidentally I do most of the work in Windows.

As for the CMAKE variables (I also am not a CMAKE expert... good with C++ but don't really like all the intricacies of deployment) I must admit I don't recognize a lot of them and they're not explicitly mentioned in the CMakeLists.txt. One thing I didn't like was the idea that when you install with CMAKE it actually installs into your distribution... so if I had installed a deb file for example, it might get into an inconsistent state...I wanted to keep them separate... so it puts everything in set(VIEWER_INSTALL_DIR "${CMAKE_BINARY_DIR}/ViewerInstall").

It sounds like Nix needs things to be put in the right place in all those Linux  /usr/bin directories etc. I sort of wonder if the best approach might be this: You pass in PACKAGE_NIX, then in CMakeLists.txt where it says:

```
# Packaging.
if (CMAKE_SYSTEM_NAME MATCHES Linux)
	if (PACKAGE_DEB)
```
we add an elseif (PACKAGE_NIX)
which basically configures a shell script called install_nix.sh.in. Could even skip the configure_file if the script didn't need the version number etc.

The difference would be inside install_nix.sh you'd basically just copy whatever files you need to the right place. I think the layout would be very similar to where the files go when packaging a deb... except thay would actually go in the real locations (instead of how create_deb.sh does it... which packages from a sandbox). This is all assuming Nix needs things in their real / locations.

Perhaps the script should be called system_install.sh instead... so it 'could' be leveraged outside of PACKAGE_NIX later on.

**Comment by bluescan** [comment]
IDK. Maybe it's a bad idea. The other option is to maybe pass in DISTRIBUTION_FILESYSTEM_LAYOUT or something, and when that's passed in actually use GNUInstallDirs which brings in all those CMAKE_INSTALL_* variables you noted above.... and then use the appropriate TYPE arguments to install as documented here: https://cmake.org/cmake/help/latest/command/install.html

The problem with this approach is I don't know when I'll have time to do it. The first option/suggestion with the shell script is probably a lot easier to get working right away.

**Comment by bluescan** [comment]
I also noticed that CMP0025 involved the compiler ID for Apple Clang. I highly doubt it will compile for apple silicon without source changes etc.

**Comment by poperigby** [comment]
From my understanding of Nix, instead of things going into `/usr`, they go into a package specific directory in `/nix/store/<package hash + name>`. During the build process, this final output directory is represented with the `$out` bash variable, so the binary should go in `$out/bin/tacentview`, and the data should go in `$out/share`. Because the CMakeLists.txt isn't respecting those variables I listed, I guess it just dumps it all into the top level directory so Tacent View doesn't know where to find anything? 

For now, I think your script idea to just manually copy over things to the right output directories once compilation is finished would work, but using GNUInstallDirs would be much appreciated once you have time 🙂.

I admit I don't know a whole lot about CMake either, so excuse me if any of this is wrong.

**Comment by bluescan** [comment]
Yeah, sounds like you got it right. I think getting it going first and look at the GNUInstallDirs later. I just pushed: 

"
Added a create_nix.sh.in file that turns into create_nix.sh after variable substitution. The substituted variables are enclosed in @ symbols. The script (without the .in extension) is then run when building so long as -DPACKAGE_NIX was passed to the configure step of cmake and install was specified when building. See https://github.com/bluescan/tacentview/wiki/Distributing
"

The wiki link at the end shows how to configure and build the install target... look for 'EXPERIMENTAL Creating a Nix package". The bash script itself is basically just the deb one renamed with a few comments. That's where you'll need to put your stuff. You can always PR after it's working. You'll probably need to figure out where the desktop icons should go as well for Nix. You can either have the script grab them from the deb_template or make a new nix_template directory with them in it.

Decided to stay with create_nix.sh.in instead of something more generic for now... as there will likely be nix-specific stuff in there. The viewer itself expects the static data to be in $NIX_DATA_DIR/tacentview/Assets (if env var is unset it (currently) uses /usr/share/tacentview/Assets

If that's not correct you'll  need to modify TacentView.cpp around line 4257 and 'ninja install' again (it will recompile the file if any changes were made). I can grant access to the repo directly if you think that's easier than PRs. Up to you.

**Comment by poperigby** [comment]
Sorry for taking a while. I'm able to create a wrapper around the executable that sets `$NIX_DATA_DIR` to the `$out` directory, so that should work great. Maybe you could make it look in `$NIX_DATA_DIR/share/tacentview`, just to keep things cleaner in the package directory?

Also, I can just perform the installation steps within the Nix package specification, so no need for a script. In fact, it's probably easier to do it without the script, as it's easier for me to debug.

I've actually gotten it to work finally!

![Screenshot_2024-08-30_20-07](https://github.com/user-attachments/assets/9dacc3ca-ebcb-4ddc-bdbd-34b8821c97e2)

**Comment by bluescan** [comment]
Super! You got it working :)

Yes, just assets were in the Assets dir. No writes or config files in this dir (just static data, button images etc). I've modified the folder for NIX builds as requested.

Disabled running the script in the cmake since it sounds like you don't need it. It's only commented out for now.

Also removed the extension from the icon spec in the desktop file. It didn't do anything bad to the deb build/install so if it it makes the icon be found on more systems, all the better.

cb674e2a4b40e534616cea17f099922199b7fac4

**Comment by poperigby** [comment]
Great! Thank you for being so helpful! I really appreciate it 🙂.

I'll create a PR on nixpkgs once you cut a release with the latest changes.

**Comment by poperigby** [comment]
Oh, I just found something out. You can actually search within the directories specified in `$XDG_DATA_DIRS` for the assets, so you don't have to have custom logic for Nix. 

From the [spec](https://specifications.freedesktop.org/basedir-spec/latest/):
> $XDG_DATA_DIRS defines the preference-ordered set of base directories to search for data files in addition to the $XDG_DATA_HOME base directory. The directories in $XDG_DATA_DIRS should be separated with a colon ':'.

So, what you would do is iterate through each directory in `$XDG_DATA_DIRS` until you find one that contains `tacentview`, and then use that for the assets directory. In most distros, `/usr/share` will be near the beginning of that list. In Nix, `/nix/profile/share` will be near the beginning.

**Comment by bluescan** [comment]
So I had actually seen that in the spec but honestly got a bit confused... especially regarding defaults. The spec says to use DATA_HOME first: "The base directory defined by $XDG_DATA_HOME is considered more important than any of the base directories defined by $XDG_DATA_DIRS." So, that means if DATA_HOME is not set, we shouldn't immediately use the DATA_HOME default, otherwise DATA_DIRS would be pointless. Fine, so we look at DATA_DIRS in order of preference.

Here's where it gets tricky: if DATA_DIRS is ALSO not set then it lists defaults (2 paths in particular, both different than the DATA_HOME default) that should be used. But if we use them, then what is the point of the spec specifying a default for DATA_HOME... it will never be used. Conversly, if DATA_DIRS is NOT set and we're supposed to use the DATA_HOME default, then the defaults for DATA_DIRS will never be used, so why does the spec specify the 2 path default?

Either I'm not understanding or the spec is ambiguous, which is not a good thing for a spec to be. It also talks about writing files to DATA_DIRS or DATA_HOME, but the data stored in there is static, so I wan't sure if this was correct place for unchanging installed static data.

Anyway, that's why I initially stayed away from reading DATA_DIRS. On a practical note, I did notice that WSL and Ubuntu do not set DATA_HOME (but do set DATA_DIRS) -- so maybe the most reasonable is to ignore the default on DATA_HOME. If DATA_HOME is set, use it. If it's not set and  DATA_DIRS is set, use the first valid DATA_DIRS path, and if DATA_DIRS is also not set, use the DATA_DIRS defaults rather than the data DATA_HOME default.

I'll LYK when I've implemented the last paragraph... but either way it would be nice to still pass in PACKAGE_NIX as packaging info is displayed in the about dialog.

**Comment by bluescan** [comment]
a863c4bbe36dc3975fde8dfc731316b39f0a9217 has it reading DATA_HOME and if not set checking DATA_DIRS in order.

**Comment by poperigby** [comment]
Awesome, works great! And you should be able to make that logic not specific to Nix, right?

**Comment by bluescan** [comment]
Glad it's working! Still not quite sure how non-Nix specific it can be RN. There are a lot of forums that suggest /usr/local for things like static files... rather than a share directory (which can be written to).

Snap has it's own set of env vars to be followed. Deb is basically just an archive so things need to go wherever the script that builds the deb says (imagine a newer deb file that updates some of the button icons or introduces new ones... the single place the static data goes needs to be updated).

Further, on Kubuntu I see 'plasma' in the first item of the data dirs... static app files surely can't be a function of whatever window manager happens to be used. The remaining install options are all portable/dev.

In any case, the logic is there (with my 'guess' as to how to handle defaults), so if needed it can be made more generic if I ever really understand where things go in Linux ;)

**Comment by poperigby** [comment]
I agree it's a bit confusing (there's a lot of outdated information on forums), but according to the [FHS spec](https://refspecs.linuxfoundation.org/FHS_3.0/fhs/ch04s11.html) (which is the specification the majority of distros use) and my own experience of using non-NixOS Linux distros, `/usr/share` is definitely the correct place to put read-only program data. From the spec:

> Any program or package which contains or requires data that doesn't need to be modified should store that data in /usr/share (or /usr/local/share, if installed locally). It is recommended that a subdirectory be used in /usr/share for this purpose. Applications using a single file may use /usr/share/misc.

A .deb file should install the data to the correct place if setup correctly, and Debian will put `/usr/share` into `XDG_DATA_DIRS` (I just span up a Debian VM and checked). So you're good to go for Debian derived distros.

As for Snap, as far as I can tell, you still need specific logic for that. But for pretty much any other distro you're in good shape just using `XDG_DATA_DIRS`.

**Comment by bluescan** [comment]
Thanks for the detailed explanation! Sounds good to me :)  I'll make the change and test a deb install sometime in the next few days. Will also let you know when there's a release with all this in it.. there's no harm in the next release being 'iterative' so won't wait too long.

**Comment by bluescan** [comment]
I hope this isn't an issue, but I was using /usr/share/tacentview/ (assuming XDG reported /usr/share/ for the data dir), but now it's using /usr/share/tacentview/Assets/

See #180 for details.

You may need to update the Nix scripts to reflect this.

**Comment by poperigby** [comment]
Thanks for the heads up. I updated my package.

**Comment by bluescan** [comment]
1.0.46 has been release.

**Comment by poperigby** [comment]
Great! Do you think you could make a release for Tacent as well?

**Comment by bluescan** [comment]
I can....but updating the version counts as a commit...so it'll be one
ahead of the fetch in the released viewer. In any case, yes, Ill make a
release and update the viewer cmake fetch.

**Comment by poperigby** [comment]
Thank you! I just wanted their to be an official release for both so I'm not submitting a dev build to nixpkgs.

**Comment by bluescan** [comment]
Yes, that's the right thing to do :)
v0.18.8 is available here: https://github.com/bluescan/tacent/releases
Shouldn't be any hitches.

**Comment by poperigby** [comment]
Thank you! Okay, I'll submit this to nixpkgs and then close this :slightly_smiling_face:.

**Comment by poperigby** [comment]
Alright, here it is: https://github.com/NixOS/nixpkgs/pull/341239 :partying_face: 

Thank you so much for all your help!

**Comment by bluescan** [comment]
Super... and np :)
