### ISSUE TITLE
Default LocInfo for Linux wrongly set for non-deb packages

### ISSUE THREAD

**Issue by ClangPan** [bluescan/tacentview#180]
Hello!

The new handling of the LocInfo created an issue for non-deb packages (such as ones for the Arch ecosystem), since it was trying to create and write folders within system files, crashing the program.

I would say this could be worked in combination with #178, using XDG by default for Linux builds (as even portable apps here use XDG, it's just that handy) and using the program path for the portable builds

**Comment by bluescan** [comment]
Hi ClangPan. OK. So that makes sense to me. Thinking out loud:

* Windows only supports portable right now. If plat is windows OR portable is set (regardless of plat), I'll use the portable locations (relataive to exe/elf).
* Development on Linux can be done by simply setting portable to true (windows is already handled). No problem.
* Linux builds will use the snap env vars, but ALL non-snap builds can use XDG.

I think that works. I'll submit a CL shortly. I'm planning on releasing soon so Nix can be packaged, but will wait to hear back that everything is copacetic with Arch first.

**Comment by bluescan** [comment]
446e774a276c2d3204af926364843454d387a1b3 _should_ do it: "Make all non-snap/non-portable builds use XDG on Linux."

I'll deal with the zipping part of #178 a bit later (but also b4 release).

**Comment by ClangPan** [comment]
Little error I caught here, should it be ``assetsDir = "/usr/share/tacentview/Assets";``?
![image](https://github.com/user-attachments/assets/44c22cdb-2fcd-4e87-881c-03938931c980)

**Comment by bluescan** [comment]
Hmm... you're correct... the deb template puts assets in the Assets subdir and I think I want to keep it (in case a Licences or other folder is introduced later). I'll also need to add that subdir to any dir retrieved from XDG env variables. Will have to update @poperigby regarding Nix as well (hopefully not a problem). Thanks.

**Comment by bluescan** [comment]
cd78fb874a41aa08505b66212c5a771933728e7c fixes.

**Comment by ClangPan** [comment]
Everything is working well now! Thanks ^^
