### ISSUE TITLE
[Suggestion] Multiple small suggestions

### ISSUE THREAD

**Issue by Frousties** [bluescan/tacentview#29]
Hello, first of I want to thank you for providing this great image viewer! I always struggled to find one that fitted my needs as well as this one does.

After using it for a bit, I want to make a couple of suggestions on how to improve the program even further (or at least put them as options and sorry if some of them have already been suggested!). I am running on Linux:

- ### Zooming the image doesn't take up the entire workspace:
![image](https://user-images.githubusercontent.com/26504212/158856061-dd442d67-5d17-46ff-811e-7cd89c212bd2.png)
![image](https://user-images.githubusercontent.com/26504212/158856095-1a948a42-a807-4ddf-a2ff-2e071d219507.png)
I don't know if this is deliberate, but I think it looks weird. The 'zooming area' seems to keep the image aspect ratio.

- ### Option to reset the zoom when switching image:
Pretty self-explanatory, navigating through folders with images of multiples sizes can get a bit messy because of that. Maybe put a 'default zoom mode' option in the preferences would fix that? Since zooming in or out resets it to 'Zoom user'.

- ### Option to close the program with 'Escape':
Some other image viewers have this feature (and sometimes by default), and I think it helps speeding up the workflow when going through multiple pictures.

- ### Support for non-US keyboards:
Now, I know this is a common issue with GLFW and ImGUI programs, but there are have been several workarounds posted to the ImGUI and GLFW issue trackers. I managed to make it work using a slightly 'dirty' method, but it would be nice to have this change made upstream.

- ### 'Basic View' mode doesn't restore the interface and settings as they were:
For example, when I exit 'Basic View', the 'Nav bar' disappears and the 'Auto Property Window' setting gets disabled. I don't really like that. 

- ### The DDS property editor is the same as the one for animated pictures: 
Only the option to display layers one-by-one would be needed here.
![image](https://user-images.githubusercontent.com/26504212/158862349-c647955d-cb24-47a7-8be6-d6e1f8156ce3.png)
![image](https://user-images.githubusercontent.com/26504212/158862374-49a3355b-307d-435e-a95a-bf387290a9a5.png)

- ### Option to enable 'Display Mipmaps' and 'Display Cubemap' by default when viewing DDS files:
Maybe also move those buttons to the DDS property editor window since it's the only image type that uses these options.

- ### A keybind window:
The option to rebind keys would be nice (and not all features have a keybind assigned to them currently). Maybe also add a key hint to the icons when hovering them as well?

- ### Add separators between icons:
Right now, all the icons are all just lined up next to each other and not necessarily grouped by functions. Adding separators and grouping the icons in a more sensible way will make the menu bar easier to navigate.

- ### Option to scale the UI / make the font bigger:
This is just for accessibility reasons and for people with bigger / smaller monitors.

<br><br>

I think this is everything that I wanted to say for now. None of these issues are a deal breaker by any means! But it would make the program feel even better to use this way in my opinion.

**Comment by bluescan** [comment]
Hi Frousties.  Nice to see the tool is being used. I think I pretty much agree with all your thoughts.
Zooming: Yeah, I wanted the displayable area to maintain aspect under zoom...but also not sure how much I like it either -- it especially breaks down viewing extremely narrow images.
Zoom Reset Option: Yup. Agree.
Esc to quit: Sure. FYI Alt-F4 currently works.
Non US keyboards: I don't own any...although I'm sure you can set the OS to interpret the scancodes as if it were a different layout. If you have code (messy or not), it could be attached to this issue (after a sep bug is made for it).
Basic View: I can look at that sometime.
Prop Editor and mipmap/cubemap: Orig intended for editing properties. Need to think about this one a bit. Point taken that only DDS files support mipmaps and cubemaps so why clutter the toolbar. As for the frame duration, agreed it should not be there for, say, DDS files... not sure for other 'non-animated' image types. Tiff, for example, can store multiple 'pages' (images)... and they could be used for flipbook anim. In fact, that frame duration field does actually set the value -- so you can adjust, for example, how long each frame takes and if you save as a gif, apng, etc, it will write that duration out. For tiff files it uses a custom (user) field for the duration, so if you reopen in tacentview, you will see it play with the saved duration for each frame. 
Keybind: Can put on list. It's a bit of work.
Separators: Agreed.
Scaling: Also a bit of work... cuz I know there are at least some hardcoded offsets etc for some of the UI widgets/controls.

Additional features I'm interested in:
- A proper file open/save dialog.
- Using the docking branch of IMGUI (the view/thumbnail screen is annoying since it exists on top of the workspace so to speak).

Although I haven't had a lot of time to work on the viewer lately, I definitely appreciate the well-thought-out feedback. If you'd be willing to enter each of your suggestions above as a separate issue (along with my corresponding comment) it would be helpful. I may be able to knock some of them off every now and then.

**Comment by Frousties** [comment]
Okay! I'll put an issue for each one of those!

**Comment by Frousties** [comment]
Here, all the issues now have their separate entries. I'd be happy to help for any of those if there's any need!

**Comment by bluescan** [comment]
Thanks Frousties. I got around to the basic mode restore issue. Basically it's now a seperate profile now so it can be customized however you like. For example, you can specify, say, a different slideshow duration. If you modified that duration while it was in 'basic' mode, it would stick next time you entered basic mode. In prefs you can always reset the profiles to their default values.

**Comment by Frousties** [comment]
Sounds good!

**Comment by bluescan** [comment]
Closing as they are entered individually.
