### ISSUE TITLE
[Suggestion] A keybind window

### ISSUE THREAD

**Issue by Frousties** [bluescan/tacentview#36]
The option to rebind keys would be nice (and not all features have a keybind assigned to them currently). Maybe also add a key hint to the icons when hovering them as well?

> Can put on list. It's a bit of work.

I am aware, this is kind of a luxury right now, take your time!

**Comment by bluescan** [comment]
About 70% done on this one. Currently have it so that the reset profile calls in the preferences will reset bindings too... not sure if a good idea as you can also reset from the bindings window.

**Comment by bluescan** [comment]
Note to self: Todo
1) The 'Set All Profiles' button on bindings window.
2) Warning popup if replacing existing binding.
3) Warning if removing shortcut to bring up bindings window. If menu-bar off and no menu binding key could get in situation where impossble to restore without deleting viewer.cfg
4) Give option to reset bindings in preferences.
5) Menu shortcut keys need to come from keybindings. Show first key bound (since mult keys may bind to same operation).

**Comment by bluescan** [comment]
4b93697ef537628bf352eeb56883c3378dd37015 closes. Note that the changes were extensive enough that a previous version config will be reset on load.
