### ISSUE TITLE
[Suggestion] Option to scale the UI / make the font bigger

### ISSUE THREAD

**Issue by Frousties** [bluescan/tacentview#38]
This is just for accessibility reasons and for people with bigger / smaller monitors.

> Also a bit of work... cuz I know there are at least some hardcoded offsets etc for some of the UI widgets/controls.

I haven't looked at a way to solve this either... Probably will be complicated as you say

**Comment by bluescan** [comment]
Here's a screen at 16pt. 14pt is current.  A few, but not crazy issues at 16.

![PointSize_16_Screenshot 2022-12-30 232003](https://user-images.githubusercontent.com/19311462/210129760-2e6ff642-363b-4cc0-a2e8-ca474517239b.png)

18 has more issues... but 14, 16, 18 seem like good targets for small/med/large sizes.

**Comment by bluescan** [comment]
14, 16, 18 pt working for top menu bar and bottom nav bar as of 1bdef459873c562acea69a30f4ba060759c3a3e4. Am going to need:
a) A shortcut command for easy testing (Shift + and Shift - most likely)
b) Precompute the font raster images since now 3 ttf point sizes are being processed on load and I don't want startup times to suffer, 
c) Toolbar buttons now change size, but will also need to increase (for med/large) playback control button sizes, including the buttons in the properties popup.
d) Go through all dialog/popups and ensure all 3 sizes work.

**Comment by bluescan** [comment]
a) Is done in 13c90c64e7b3e82e4512325d7d529471388773e2
Still need b) c) d).

**Comment by bluescan** [comment]
c) is done.. both properties window and main playback control. d) has the save-as dialogs done.
NW = Needs Work. CK = Check (have not looked).

About : OK
Prefs->Interface : NW
Colour Channels :  NW
Resize Canvas: NW (needs the anchor sizes and overall anchor position adjusted
Resize Image : OK
Rotate Image : OK
Crop : CK
Cheat Sheet : NW
Keyboard Bindings: NW. Most ok. Some operation descriptions too long.
Menu View -> Zoom : NW, Zoom text cut off.
Overwrite File : OK
Save Multiframe: OK
Contact Sheet : OK
