### ISSUE TITLE
.qoi images appear upside-down.

### ISSUE THREAD

**Issue by BrokenShards** [bluescan/tacentview#98]
When opening a .qoi image, it appears as if it has been flipped vertically (see attached image).
Other software such as Tev (`https://github.com/Tom94/tev`) and ImageMagick display the image in the correct orientation, as does the explorer extension (`https://github.com/iOrange/QOIThumbnailProvider`), so I am sure it is not an issue with the conversion from .png.
![tacent error](https://user-images.githubusercontent.com/7679633/226128981-80368a6f-8eb8-4fd7-9614-f9e2cfec68c1.png)

**Comment by bluescan** [comment]
Huh. You're right. I didn't notice because tacent-view is also saving them upside-down as well... so when they loaded back in they looked correct ;)  Hold on.

**Comment by bluescan** [comment]
This is fixed in: 73897031dc920004be533af1345ff6ca57df2475

I've attached a zip of this build in case you want to test before the next release... although I'll probably release in the next week or two as this issue plus a webp-loading issue are fairly important. Thanks for the report!

[tacentview_1.0.36.zip](https://github.com/bluescan/tacentview/files/11017035/tacentview_1.0.36.zip)

**Comment by BrokenShards** [comment]
That has fixed the issue, thanks very much for your quick response!
